version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data

  pruebas:
    volumes:
      - ./pruebas/:/mnt/
    build: ./pruebas
    working_dir: /backend/
    command: sh run_queries.sh

  monitor-pruebas:
    volumes:
      - ./monitor-pruebas/:/mnt/
      - ./monitor-pruebas/output:/backend/output
    build: ./monitor-pruebas
    working_dir: /backend/
    command: sh run.sh
    env_file: 
      - ./monitor-pruebas/monitor.env
    depends_on:
      - pruebas
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - pruebas
