version: '3'

services:
  rabbitmqServer:
    container_name: rabbitmqServer
    image: "rabbitmq:3-management"
    hostname: "rabbitmq-host"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pass"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      rabbitmqServer:
        condition: service_started
      receiver:
        condition: service_started
    ports:
      - 7000:7000
    environment:
      RABBITMQ_USERNAME: "admin"
      RABBITMQ_PASSSWORD: "pass"
      RABBITMQ_HOST: rabbitmqServer
      RABBITMQ_QUEUE: dataqueue
      RABBITMQ_ROUTING_KEY: dataqueue 
      RABBITMQ_EXCHANGE: exchange_test
      SERVER_PORT: 7000
      SERVER_HOST: receiver
    restart: always
    healthcheck:
      interval: 10s
      timeout: 5s

  receiver:
    container_name: receiver
    build:
      context: ./receiver
      dockerfile: Dockerfile
    restart: always
    depends_on:
      rabbitmqServer:
        condition: service_started
    ports:
      - 8000:8000
    environment:
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSSWORD: pass
      RABBITMQ_HOST: rabbitmqServer
      RABBITMQ_QUEUE: dataqueue
      RABBITMQ_ROUTING_KEY: dataqueue 
      RABBITMQ_EXCHANGE: exchange_test

  usuarios:
    volumes:
      - ./usuarios/:/mnt/
    build: ./usuarios
    working_dir: /backend/
    command: sh run_queries.sh

  nginx:
    image: nginx:latest
    ports:
      - 5000:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
        - usuarios

  certificador:
    volumes:
      - ./certificador/:/mnt/
      - ./certificador/output:/backend/output
    build: ./certificador
    working_dir: /backend/
    command: sh run.sh
    env_file: 
      - ./certificador/monitor.env
    depends_on:
        - usuarios