version: "3.7"
services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 5000:80
    restart: always
    environment:
      # Only used for / redirect to default webapp
      - NGINX_PUBLIC_HOST=localhost:5000
      #- NGINX_PUBLIC_HOST=apps.titellus.net
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app

  # api_test:
  #   build: ./api_test
  #   restart: always
  #   ports: 
  #     - '5000:5000'
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    # command: gunicorn -w 3 -t 60 -b 0.0.0.0:5001 app:app

  flask_app:
    build: './flask_app'
    # ports:
    #   - "5000:5000"
    depends_on:
      - rabbit

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    # volumes:
    #   - rabbitmq_3_data:/var/lib/rabbitmq/
    #   - rabbitmq_3_log:/var/log/rabbitmq

  simple_worker:
    build: './simple_worker'
    user: nobody
    depends_on:
      - rabbit
      - flask_app
  
  
